#frase = ('Curso em Vídeo Python')
#print(frase.replace('Python', 'Android'))
#print(frase.upper())
#print(frase[5:7])
#print(frase.lower())
#print(frase.capitalize())
#print(frase.title())
frase =('   Aprenda Python  ')
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())